@baseUrl = http://localhost:3000/api

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "John Rocha",
  "email": "john@email.com",
  "password": "123456"
}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "ana@email.com",
  "password": "123456"
}

###

GET {{baseUrl}}/auth/me
Authorization: Bearer {{login.response.body.$.accessToken}}

###

POST {{baseUrl}}/todos
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

{
  "title": "Estudar NestJS",
  "description": "Criar minha primeira tarefa autenticada"
}

###

GET {{baseUrl}}/todos
Authorization: Bearer {{login.response.body.$.accessToken}}