@baseUrl = http://localhost:3000/api

POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "John Rocha",
  "email": "john@email.com",
  "password": "123456"
}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "john@email.com",
  "password": "123456"
}

###

GET {{baseUrl}}/auth/me
Authorization: Bearer {{login.response.body.$.accessToken}}

###

# @name createTodo
POST {{baseUrl}}/todos
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

{
  "title": "Estudar Flutter",
  "description": "Estudar o framework Flutter para desenvolvimento de aplicativos móveis."
}

###

GET {{baseUrl}}/todos
Authorization: Bearer {{login.response.body.$.accessToken}}

###

GET {{baseUrl}}/todos?page=1&limit=10
Authorization: Bearer {{login.response.body.$.accessToken}}

###

GET {{baseUrl}}/todos?completed=false
Authorization: Bearer {{login.response.body.$.accessToken}}

###

GET {{baseUrl}}/todos?completed=true
Authorization: Bearer {{login.response.body.$.accessToken}}

###

GET {{baseUrl}}/todos?search=nest
Authorization: Bearer {{login.response.body.$.accessToken}}

###

GET {{baseUrl}}/todos?sortBy=createdAt&order=asc
Authorization: Bearer {{login.response.body.$.accessToken}}

###

GET {{baseUrl}}/todos?sortBy=title&order=asc
Authorization: Bearer {{login.response.body.$.accessToken}}

###

GET {{baseUrl}}/todos/{{createTodo.response.body.$.todo.id}}
Authorization: Bearer {{login.response.body.$.accessToken}}

###

PATCH {{baseUrl}}/todos/{{createTodo.response.body.$.todo.id}}
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

{
  "title": "Estudar Flutter com NestJS",
  "description": "Atualizando uma tarefa existente",
  "completed": true
}

###
DELETE {{baseUrl}}/todos/1f4e96e6-1a98-4211-8902-6a57a10fb0b4
Authorization: Bearer {{login.response.body.$.accessToken}}